### ISSUE TITLE
Relative state for switch

### ISSUE THREAD

**Issue by bruno-villa** [Luligu/zigbee2mqtt-automations#1]
**Is your feature request related to a problem? Please describe.**
Hi, thank you for this project, looks very promising for simple systems without running HA or similar in parallel to zigbee2mqtt. I'm trying to set up a switch to control brightness and color temperature. The switch offers the actions `press_1`, `release_1`, `press_2`, `release_2`, `press_3`, `release_3`, `press_4`, `release_4`. I can define a very basic rule to adjust e.g. brightness by triggering on these actions. My question is whether it is possible to have a payload contain a relative value instead of an absolute one. That is, the switch could act like a normal dimmer, being aware of what the current brightness is. 

**Describe the solution you'd like**
I'd like to define rules that change brightness and color temperature relative to the current values. Not sure if that is supported with a parcticular syntax in the mqtt messages, or if the extension would need a new feature for that. 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Luligu** [comment]
Hi,
I'm not sure if I understood correctly. 
In the payload you can put every command you want not only the state and brightness or color_temp. The payload is passed like it is. So if your device support it you can use for instance the brightness_move_onoff.
Here is how I use it on my automations:

Guest room Occupancy sensor TRUE guests OFF:
  active: true
  trigger:
    entity: Guest room Occupancy sensor
    attribute: occupancy
    state: true
  condition:
    - entity: Guest room Occupancy sensor
      attribute: illuminance
      below: 60
    - entity: At home
      state: ON
    - entity: Guests
      state: OFF
  action:
    - entity: Guest room Desk light strip
      payload: { brightness_move_onoff: 40, color_temp: 500 }
    - entity: Guest room Wardrobe light strip
      payload: { brightness_move_onoff: 40, color_temp: 500 }

Guest room Occupancy sensor FALSE guests OFF:
  active: true
  trigger:
    entity: Guest room Occupancy sensor
    attribute: occupancy
    state: false
    for: 300
  condition:
    - entity: Guests
      state: OFF
    - entity: Guest room Lights
      state: OFF
  action:
    - entity: Guest room Desk light strip
      payload: { brightness_move_onoff: -10 }
    - entity: Guest room Wardrobe light strip
      payload: { brightness_move_onoff: -10 }

This turn on the lights (they are both RGB CTT light strips) at a speed of 40 units per sec and turn them off with a 10 units per second speed.
Other zigbee commands could work as well. I don't use them but you can experiment with brightness_step_down or color_temperature_move for example.

Let me know if you find some interesting solution please.

**Comment by bruno-villa** [comment]
Thank you, maybe it's just me being unfamiliar with zigbee2mqtt. Will try your examples later in the week and update. Cheers.

**Comment by chris-1243** [comment]
@bruno-villa  what kind of zigbee device are you using? It looks like an Enocean PTM215Z or similar.

@Luligu Would you think it is possible to use the elapsed function in zigbee2mqtt ? This kind of device always send the press_x and release_x on each click. I am not an expert at all but this how it works via homeassistant. I guess we may reproduce it and for small and not so complex environment, it could be a great option.

**Comment by Luligu** [comment]
The occupancy sensor is a Aqara P1 human body movement and illuminance sensor.

**Comment by bruno-villa** [comment]
Hi, 
indeed this is regarding an [EnOcean PTM 215Z](https://www.zigbee2mqtt.io/devices/PTM_215Z.html). With the move payload it is straightforward to set dimming and color temperature (below). 
Additionally I'd like to have a short press toggle state ON and OFF. ON should be straightforward by adding it to the payload bound to the `press_1` event. However, not sure how to go about OFF. I'm not familiar with HA or the elapsed function but that'd be suitable. Alternatively proxying it by some relative measurement of brightness, so if the brightness did not change much between press and release the payload OFF should be sent. 

There are various issues on the zigbee2mqtt repo. For example https://github.com/Koenkk/zigbee2mqtt/issues/13361#issuecomment-1202159610 shows a solution with NodeRed, but I'm not seeing how it'd translate to these automations. 

```yaml
mygroup_dim_up:
  trigger:
    entity: switch mygroup
    action: press_1
  action:
    - entity: mygroup spots
      payload: { brightness_move: 40 }
mygroup_dim_up_stop:
  trigger:
    entity: switch mygroup
    action: release_1
  action:
    - entity: mygroup spots
      payload: { brightness_move: 0 }
mygroup_dim_down:
  trigger:
    entity: switch mygroup
    action: press_2
  action:
    - entity: mygroup spots
      payload: { brightness_move: -40 }
mygroup_dim_down_stop:
  trigger:
    entity: switch mygroup
    action: release_2
  action:
    - entity: mygroup spots
      payload: { brightness_move: 0 }
```

**Comment by chris-1243** [comment]
For the moment, I do use automation made by the community in HA. It is working well. I was also wondering how to translate it directly to Z2M via this project.

In HA and as far as I dig in the code (with my poor knowledge...), the elasped function is used this way:
 - if elapsed <500ms, you send an ON command or anything else you configured
- if elasped >500ms, then the hold function is simulated and you may send a "brightness_move" payload with press_x and "brightness_move: 0" with release_x
[](https://gist.github.com/vandalon/d2a327297d579b304549e96c66765992)

I was stuck on the OFF command when I tried. I played with the state of the light for the ON command.

**Comment by Luligu** [comment]
Hi, it seems really interesting to add this function. 
When you say elapsed what does it mean exactly? Elapsed since what moment? Like a double command to execute immediately and a second after 500ms? That would be interesting for some devices that have the usual problem to turn the state when you move the brightness. Let me know.

**Comment by chris-1243** [comment]
Here from zigbee2mqtt "MQTT behaviour"
 _# Optional: Add an elapsed attribute to MQTT messages, contains milliseconds since the previous msg (default: false)
  elapsed: false_


From Zigbee2mqtt logs:
_info  2023-12-18 15:43:39: MQTT publish: topic 'zigbee2mqtt/Switch Cuisine/action', payload 'press_4'
info  2023-12-18 15:43:39: MQTT publish: topic 'zigbee2mqtt/Switch Cuisine', payload '{"action":"release_4","device":{"friendlyName":"Switch Cuisine","ieeeAddr":"0x000000000170beb2","manufacturerID":null,"model":"PTM 215Z","networkAddress":48818,"type":"GreenPower"},**"elapsed":261**,"linkquality":25}'


[[Zigbee2MQTT enOcean PTM 215Z (Friends of Hue) switch](https://community.home-assistant.io/t/zigbee2mqtt-enocean-ptm-215z-friends-of-hue-switch/429770)](https://community.home-assistant.io/t/zigbee2mqtt-enocean-ptm-215z-friends-of-hue-switch/429770))

I guess with those information, you may be able to understand a bit better how this function works.

As the device we are talking (PTM215Z or PTM216Z) is always sending press_x then release_x, the "elapsed function" measures the time (in ms) between those two messages. Then, it should be possible to emulate a "press_x_hold" function.

**Comment by bruno-villa** [comment]
Would be really cool if that can be added. I also think the only way to tell is to extend the `release` action to differentiate it based on the time elapsed since the `press` action. 
Perhaps in the config something along the lines of
```yaml
mygroup_dim_down:
  trigger:
    entity: switch mygroup
    action: press_2
  action:
    - entity: mygroup spots
      payload: { brightness_move: -40 }
mygroup_dim_down_stop:
  trigger:
    entity: switch mygroup
    action: release_2
  condition:
    delay:
      trigger:
        entity: switch mygroup
        action: press_2
      # Delay since condition.delay.trigger event in ms, inclusive
      above: 500
  action:
    - entity: mygroup spots
      payload: { brightness_move: 0 }
mygroup_off:
  trigger:
    entity: switch mygroup
    action: release_2
  condition:
    delay:
      trigger:
        entity: switch mygroup
        action: press_2
      # Delay since condition.delay.trigger event in ms, exclusive
      below: 500
  action:
    - entity: mygroup spots
      payload: { state: OFF }
```
