### ISSUE TITLE
Multiple Action Feature

### ISSUE THREAD

**Issue by mrmaximas** [Luligu/zigbee2mqtt-automations#14]
Hi! Thanks for this amazing tool 🙏🏻
It's possible/how to made multiple action in one automation? 
For example, i need to close 3 water valves at the same tiime from 3 leak sensors event.

**Comment by mrmaximas** [comment]
@helderfmf thanks for you reply.
I have three leak sensors and three water valves, when any sensor is triggered all three valves must be closed. now it's 9 (nine) automations ;)

```
Bathroom Leak - Valve Cold:
  active: true
  trigger:
    entity: Bathroom Leak 
    attribute: water_leak
    equal: true
  action:
    entity: Valve Cold
    payload: { state: OFF }
    logger: info

Bathroom Leak - Valve Hot 1:
  active: true
  trigger:
    entity: Bathroom Leak 
    attribute: water_leak
    equal: true
  action:
    entity: Valve Hot 1
    payload: { state: OFF }
    logger: info

Bathroom Leak - Valve Hot 2:
  active: true
  trigger:
    entity: Bathroom Leak 
    attribute: water_leak
    equal: true
  action:
    entity: Valve Hot 2
    payload: { state: OFF }
    logger: info

Shower Leak - Valve Cold:
  active: true
  trigger:
    entity: Shower Leak 
    attribute: water_leak
    equal: true
  action:
    entity: Valve Cold
    payload: { state: OFF }
    logger: info

Shower Leak - Valve Hot 1:
  active: true
  trigger:
    entity: Shower Leak 
    attribute: water_leak
    equal: true
  action:
    entity: Valve Hot 1
    payload: { state: OFF }
    logger: info

Shower Leak - Valve Hot 2:
  active: true
  trigger:
    entity: Shower Leak 
    attribute: water_leak
    equal: true
  action:
    entity: Valve Hot 2
    payload: { state: OFF }
    logger: info

Kitchen Leak - Valve Cold:
  active: true
  trigger:
    entity: Kitchen Leak 
    attribute: water_leak
    equal: true
  action:
    entity: Valve Cold
    payload: { state: OFF }
    logger: info

Kitchen Leak - Valve Hot 1:
  active: true
  trigger:
    entity: Kitchen Leak 
    attribute: water_leak
    equal: true
  action:
    entity: Valve Hot 1
    payload: { state: OFF }
    logger: info

Kitchen Leak - Valve Hot 2:
  active: true
  trigger:
    entity: Kitchen Leak 
    attribute: water_leak
    equal: true
  action:
    entity: Valve Hot 2
    payload: { state: OFF }
    logger: info
```

**Comment by mrmaximas** [comment]
@helderfmf Parece-me que deve funcionar! Vou ver amanhã. Muito obrigado!

```
Leak:
  active: true
  trigger:
    - entity: Bathroom Leak 
      attribute: water_leak
      equal: true
    - entity: Shower Leak 
      attribute: water_leak
      equal: true
    - entity: Kitchen Leak 
      attribute: water_leak
      equal: true
  action:
    - entity: Valve Hot 1
      payload: { state: OFF }
      logger: info
    - entity: Valve Hot 2
      payload: { state: OFF }
      logger: info
    - entity: Valve Cold
      payload: { state: OFF }
      logger: info
```

```
Info 2025-03-19 22:50:55z2m: [Automations] Registering event automation [Leak] trigger: entity #Bathroom Leak#
Info 2025-03-19 22:50:55z2m: [Automations] Registering event automation [Leak] trigger: entity #Shower Leak#
Info 2025-03-19 22:50:55z2m: [Automations] Registering event automation [Leak] trigger: entity #Kitchen Leak#

```
