### ISSUE TITLE
TURN_OFF_AFTER not working properly

### ISSUE THREAD

**Issue by helderfmf** [Luligu/zigbee2mqtt-automations#16]
**Describe the bug**
Turn_off_after not working as intended, because I doesn't store the all the information of the first action, it just sends a generic turn_off to the device, in case of a simple relay this could work, but in my case, I have multiple channels for the wall switch, it doesn't do nothing.

**To Reproduce**
Have this automation for my sensor to turn on the right switch of my Aqara doble rocker lumi.switch.b2nc01

```
Luz Sala Hall Movimento ON:
  trigger:
    entity: Sala hall sensor
    attribute: occupancy
    equal: true
  condition:
    - after: 18:30:00
    #- before: 08:00:00
  action:
    - entity: Sala hall interruptor duplo
      payload: { state_right: on }
      turn_off_after: 30
``` 

**Expected behavior**
Expected to turn off the right switch of the Aqara after the 30s, but instead it sends a STATE:OFF to the switch without specifying which channel to turn off, so it does nothing.

**Screenshots**
Debug action from Automations
[2025-03-16 18:59:53] debug: 	z2m: [Automations] Turn_off_after timeout for automation [Luz Sala Hall Movimento ON] send { "state": "OFF" } to entity #Sala hall interruptor duplo# 

**Additional context**
Some other problem I am facing is with condition, if I put after and before, like in you exemples, it doesn't trigger.
Have to comment it out to work, maybe because they are mutually exclusive, and both cannot be true for the same day, it should be a way to evaluate one **OR** the other.
What I would like to use in conditions, is after sunset and before sunset, it is more dynamic and makes more sense, but didn't find any example for condition, only for triggers.
