### ISSUE TITLE
turn_off_after with the condition or something else.

### ISSUE THREAD

**Issue by mrmaximas** [Luligu/zigbee2mqtt-automations#17]
I want to realise the following automation in the bathroom:
1. On the triggered of the contact sensor (toilet flushing) the fan is turn-on.
2. The fan turn-on for 5 minutes.
3. If the humidity in the bathroom after 5 minutes is higher than the set humidity (someone is washing in the shower), the fan does not turn off, but continues to work.
If the humidity in the bathroom after 5 minutes is not higher than the set point (no one has showered) - the fan turn off.
 Is it possible to add a condition to turn_off_after or something else?
Thanks!

**Comment by Luligu** [comment]
Not directly but you can add an automation to turn off the fan after 5 minutes the humidity is lower then the limit.

**Comment by mrmaximas** [comment]
@Luligu Hi! Please explain the logic behind Turn_off_after.
If the occupancy trigger is activated, a payload will be sent after 60 seconds. 
What will happen if the trigger is activated again after 30 seconds for example? 
Will the light turn off after the next 60 seconds or the remaining 30 seconds? 
If this happens in 30 seconds, can this logic be corrected?

```
Motion in the hallway with custom payload_off:
  active: true
  trigger:
    entity: Hallway motion sensor
    attribute: occupancy
    equal: true
  action:
    entity: Hallway light
    payload: turn_on
    turn_off_after: 60
    payload_off: { state: "OFF" }
    logger: info
```
