### ISSUE TITLE
Toggle off doesn't work with Aquara mini switch

### ISSUE THREAD

**Issue by bonzenpaule** [Luligu/zigbee2mqtt-automations#19]
**Describe the bug**

Hello!
An hour ago I updated my zigbee2mqtt from version 2.1.3-1 to version 2.2.1-1 and a bug appeared for me.

I have two kind of "trigger devices" in my home to start automations:
 - Aquara mini switch T1 [WXKG13LM](https://www.zigbee2mqtt.io/devices/WXKG13LM.html#aqara-wxkg13lm)
 - Hue wall switch [929003017102](https://www.zigbee2mqtt.io/devices/929003017102.html#philips-929003017102) (they are all configured to work as "rocker")

For those "trigger devices" I have automations to toggle entities (lights and switches) on and off again.

Since the update of zigbee2mqtt the automations triggered with the Aquara mini switches won't turn the entities off anymore. 

When the entity, e.g. light, is off the automations work flawelessly. The trigger is registered and the light turns on. But pressing the trigger again doesn't turn the light off again. Yesterday, before updating zigbe2mqqt, the automations worked for both devices.

My automations for both are similar. Here are two examples:
For an Aquara mini switch:
```
Küche_Lichtschalter_Kommodenlampe:
  trigger:
    entity: Küche_Lichtschalter_Kommodenlampe
    attribute: action
    equal: single
  action:
    - entity: Küche_Kommodenlampe
      payload: { state: toggle, brightness: 190, color_temp: 384, transition: 1 }
```
For an Hue wall switch:
```
Schlafzimmer_Lichtschalter:
  trigger:
    entity: Schlafzimmer_Lichtschalter
    attribute: action
    equal: left_press
  action:
    - entity: Schlafzimmer_Stehlampe
      payload: { state: toggle, brightness: 115, color_temp: 384, transition: 1 }
    - entity: Schlafzimmer_Deckenlampe
      payload: { state: toggle, brightness: 115, color_temp: 384, transition: 1 }
```

When pressing the trigger the device goes off for a milisecond and then on again. For Homeassistant (in the UI) the device is off but in reality it's still on.

The only way to truely turn them off after this, is to turn the device back on through the HA UI (so that they are on the same page again: Device on in reality and on in HA) and then off again.

**BUT**: This bug only appears for the aquara mini switches. The automations for the hue wall switch are still working as expected. The first press / trigger turns the light on and the second press / trigger turns them off again.

So I'm wondering if this is more related to zigbe2mqqt than to your plugin. If it is and this post is in the wrong location then I will try again in the zigbe2mqtt github. I've found no matching issues for "toggle" in the z2m github, that's why I'm opening a new issue here.

Any help is welcome! Thanks in advance. :)

**Additional context**
- HA Green
- HA Core: 2025.4.3
- HA OS: 15.2
- Zigbe2MQTT: 2.2.1-1
- zigbee2mqtt-automations: 2.0.2
- SONOFF Dongle-P
